### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by TechieLibra** [UGA-BSAIL/plant_3d_deep_learning#6]
Could you please provide clustering code for number of cotton balls

**Comment by FarahSaeed** [comment]
It is [here](https://github.com/UGA-BSAIL/plant_3d_deep_learning/blob/main/plant_part_segmentation/trait_extraction/traitExtraction_POS_num_cotton_bolls.m).

**Comment by TechieLibra** [comment]
Thanks
