### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by chan-k-346** [UGA-BSAIL/plant_3d_deep_learning#7]
Nice to meet you, I found a wonderful piece of software.
We would like to use PLANTCLOUD. I saw the video from https://github.com/UGA-BSAIL/plant_3d_deep_learning/blob/main/plant_annotation/README.md and downloaded it, but the following error was confirmed when running the OpenGL.exe file failed.
・The code execution cannot proceed because VCRUNTIME140_1D.dll was not found. Reinstalling the program may fix this problem.
・The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstalling the program may fix this problem.
・The code execution cannot proceed because ucrtbased.dll was not found. Reinstalling the program may fix this problem.

On the Internet, it was written that I needed to install Microsoft Visual C++ Redistributable.
I also have Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022 (latest) on my PC.
Could you please tell me how to solve this?

**Comment by FarahSaeed** [comment]
Hi 

I should try to share a recompiled version if I see no errors while recompiling. Thanks.

**Comment by chan-k-346** [comment]
Thank you for your reply.
Looking forward to the recompiled version.

**Comment by FarahSaeed** [comment]
done [here](https://github.com/UGA-BSAIL/plant_3d_deep_learning/tree/main/plant_annotation).

If there are still any errors, feel free to reopen the issue.
